### ISSUE TITLE
「設定をファイルから復元」でregファイル一覧が表示されない

### ISSUE THREAD

**Issue by taka-ot** [sayurin/ffftp#20]
・該当フォルダにregファイルは存在するが一覧に表示されない
・入力欄に頭の文字を入れると候補は表示される
　この候補を選択すると、正常に復元できる

**Comment by sayurin** [comment]
`'\0'`を含む文字列がUTF-8→UTF-16変換の途中で切れてしまっている可能性がある。

**Comment by sayurin** [comment]
そもそもリソースファイルの時点で抜け落ちていました。
またリソースファイルは `'\0'` を扱える（ことを確認していた）ものの、末尾の `'\0'` は消されてしまうことが判明しました。
リソースの保持方法から変更します。

**Comment by sayurin** [comment]
[リソースは末尾含め `'\0'` を正しく扱える](https://blogs.msdn.microsoft.com/oldnewthing/20091008-00/?p=16443)とのこと。UTF-8変換の際に消されている模様。
となると #10 mbswrapper.cpp を使わない実装に切り替える必要がある。今回の場合は、`GetOpenFileName`と`GetSaveFileName`を回避する。

**Comment by sayurin** [comment]
「リソースは末尾含め `'\0'` を正しく扱える」というようなことはなく、やはり

> リソースファイルは `'\0'` を扱える（ことを確認していた）ものの、末尾の `'\0'` は消されてしまうことが判明しました。

が正しかったようです。

**Comment by sayurin** [comment]
#23 で修正。
