### ISSUE TITLE
ファイル・アップロードで必ずエラーダイアログが表示される

### ISSUE THREAD

**Issue by taka-ot** [sayurin/ffftp#21]
エラーを表示しているダイアログの各ボタンをクリックすると以下の動作となる
・「OK」をクリックすると、再度同じエラーダイアログが表示される
・「以降全て」をクリックすると、エラーダイアログを自動的に表示し続ける無限ループに入る
・「全て中止」をクリックすると、エラーダイアログが消えると同時に、ファイルのアップロードが完了する

**Comment by nnkanegon** [comment]
3.1ですが、同じ現象が発生しています。
remote.cpp内のSendData()で、Size==0のときはFFFTP_SUCCESSを返して欲しい気がします。
