### ISSUE TITLE
Win10 64Bit環境のFFFTP64bit版では「設定をレジストリでなくINIファイルに保存する」が機能しない

### ISSUE THREAD

**Issue by Phamrage** [sayurin/ffftp#30]
Windowsの制約でProgram Filesフォルダへの書き込みは出来ない為

**Comment by sayurin** [comment]
各仕様は次の通り

- Program Files は読み取り専用
- Program Files (x86)も読み取り専用だがフォルダリダイレクトにより書き込みできたかのようにアクセスできる
- ffftpのiniファイルは実行ファイルと同じフォルダから読み込む

このためINIファイルを使用するには最終的にはProgram Files外にインストールしていただくことになるでしょうか。

次善策として書き込み不可フォルダにインストールされている場合にはINIファイルに保存するメニューを無効化することでしょうか。ただしフォルダリダイレクトを受けると書き込み権の無いフォルダであっても書き込み可能なので判定が難しいですね。
次点で書き込み失敗時に説明をすることでしょうか。

---
別アプローチとして

- iniファイルの場所を変更する（`%LOCALAPPDATA%`等）
- ポータブル版（zip版）とメニュー構成を変更し、.msi版はレジストリ必須、.zip版はini必須と棲み分けする

も考えられる。

**Comment by Phamrage** [comment]
INIファイルはPCの引っ越しの時に(個人としても他の人のサポートとしても)重宝しています。現状では64BIT環境でも32BIT版を利用して、問答無用でINI保存を有効にして(させて)ます。
MSのWinアプリのフォルダ利用お作法ガイドもあるみたいですが、ポータブルを考慮するとそのまま適用は難しいと思うので最初からユーザに保存場所を指定させてしまう、というのでも良いかもしれません。

**Comment by sayurin** [comment]
@Phamrage ポータブル版（ZIP版）であれば利用者が展開を行うので、EXEを展開できる＝書き込み可能なフォルダであり、その場合はもちろんINIも書き込み可能なわけです。今回のエラーはMSI版を使われたということでしょうか？ このような用途ではやはりポータブル版を使用し、書き込み可能なフォルダーに展開されることをお勧めします。

> 最初からユーザに保存場所を指定させてしまう

**INIファイルがどこに保存されているのか**という情報が保存できないので実現できません。またiniファイルを特定の場所に変更するというのも不可能ではありませんが、フォルダ一式だけで完結するというポータブル版の利点を損なうのであまり現実的ではありません。

**Comment by juner** [comment]
firefox や Chrome の様な管理者権限無し時のインストールの動作と同様に %LOCALAPPDATA% の下にインストールすることが出来るようになれば解決するとかそういう話だったりますでしょうか？

**Comment by sayurin** [comment]
ポータブル版を使用してもらうということでcloseします。

**Comment by itagagaki** [comment]
ポータブル版を使用してもらうということですが、ダウンロード前にわかるように、もっと周知したほうが良いのでは？
私は忘れっぽいので毎回この問題に引っかかってしまいます。

**Comment by sayurin** [comment]
@itagagaki 良かったら、どういったことを求めているのか、 #249 で説明していただけないでしょうか。ダウンロードページで解決すべき問題なのか少し引っかかります。
