### ISSUE TITLE
アップロードしたファイルのタイムスタンプが1年前になってしまう

### ISSUE THREAD

**Issue by honeylover** [sayurin/ffftp#32]
海外在住者です。
日本のサーバーにアップロードするとある条件下で一時的にサーバー側のファイルのタイムスタンプが1年前になってしまう（1日以内に戻る）という現象が起きています。

たまに二人で作業することもあるためミラーリングは必須なのですが、上記現象ゆえに困っています。何とか解決方法があるならとてもありがたいです。
現在は、アップロードの時間を制限して、00:00～10:59だけにしています。11:00～23:59の間はアップロードしないように気を付けているような状況です。

---
https://osdn.net/projects/ffftp/forums/27005/39434/ から転載

ある条件下でサーバーにアップロードしたファイルのタイムスタンプがちょうど1年前になってしまいます。日付及び時刻は同じです。ただし、しばらくすると（9時間後？）、正常な年に戻ります。実はこの問題はかなり古いバージョン（10年以上前）にもあって、当時、作者にも問い合わせましたが、結局未解決のままでした。

ところが、昨日、FFFTPでは1年前(2017年)として表示されているのに、Filezillaというソフトで見てみるとちゃんと2018年と表示されているのを発見。つまり、やはり何か方法があるのかもしれないと思い、こちらで聞いてみることにしました。

ちなみに私はいま、ブラジルの GMT -4:00 の地域におります。つまり現在日本とは13時間差があります。こちらが遅れています。左右ペインの日時を合わせるためにホストのタイムゾーンはGMT +9:00 (日本)にしていますが、どういう設定にしてもこの特定条件下での1年ずれ現象に変化はないことは確認済です。

タイムスタンプが1年前になってしまうには条件があるようです。ちょっとややこしいですが説明してみます。

ファイルのタイムスタンプが送信日当日のもので、かつ、こちらの日付と日本（サーバー）の日付が1日ずれているときに上記の1年ズレの現象が起きるようです。日本の日付が変わったとき（つまり現地時間の午前11時）からこの現象が起きることを確認しています。たとえば、2018/04/20 10:59 というタイムスタンプのファイルを 11:01にアップロードすれば、2018/04/20 のままですが、タイムスタンプが 2018/04/20 11:00 のファイルは 2017/04/20 11:00 と表示されるようになります。

そして数時間後に本来の日時2018/04/20 11:01になるということです。この「数時間」が何時間かは未確認ですが、9時間という情報も見ました。なかなかちょうどの時間にPCの前にいられないので明確な時間はまだ分かっていません。

どんなふうになるかスクショ取りました。
![ffftp 3](https://user-images.githubusercontent.com/3615855/39384279-2a0c6448-4aa7-11e8-806a-af0b9be8f35a.gif)

ちなみに、Filezillaでは全部正常に表示されているのですが、サーバー設定の「サーバのタイムゾーン オフセットの調整」はゼロのままです。ここを9時間とすると右ペイン（サーバー側）の時間が9時間プラスになってしまいます。

タイムスタンプが1年前だとミラーリングの時に都合が悪くて困っています。単に表示上だけでなく本当に1年前の日付として判断されてしまうのです。

**Comment by honeylover** [comment]
お返事ありがとうございます！
マト・グロッソ・ド・スル州です。夏時間の適用地域ですが、今は通常時間です。

PCのタイムゾーンは、「(UTC-04:00) クイアバ」となっており、現在は日本とは13時間差があります。
FFFTPの設定についてですが、ホストの設定 - 拡張タブ - ホストのタイムゾーン は GMT+9:00 (日本) になっています。そうしないと、左右のペインで見かけ上の時間差が出てしまいます。

なお、余計なことかもしれませんが、ここのタイムゾーンを変えても、見かけ上の時間差が生じるだけで、ミラーリングの時には同じタイムスタンプと見なしているようです。

**Comment by honeylover** [comment]
もう一つ。あちらから転載＋編集です。現地時間で21日になったときに書いたものです。

本来の年に戻るのはアップロードして何時間とかではありませんでした。いまこちらで21日になった瞬間に1年前になっていた全ファイルの年が2017から2018に変わりました。つまり、日が現地と日本で同じになったからだと言えると思います。

ですので、0:00から10:59まではアップロードしても問題なく、11:00から23:59（0時）までは、問題が生じるということです。それも、アップロードする日とファイルのタイムスタンプの日が同じとき（基本的に自分で更新したばかりのファイルをすぐにアップロードするときなど）に生じるという、限定された条件下のみで発生するということが分かりました。

**Comment by sayurin** [comment]
> 本来の年に戻るのはアップロードして何時間とかではありませんでした。いまこちらで21日になった瞬間に1年前になっていた全ファイルの年が2017から2018に変わりました。

サーバー上は正しい時刻で保存されており、ffftpを通して参照すると時間帯によって得られる結果が異なって見える。つまり、ffftp側の解釈に誤りがあるように見える。

ということで正しいでしょうか？ FTPはサーバーから渡された文字列を人間が目で判断する仕様です。その判断ロジックにバグがあるのかもしれません。

**Comment by honeylover** [comment]
技術的なところまでは何とも言えませんが、Filezillaでは何時でも普通に2018年として取得されているのは事実です。だとすると、判断ロジックに何らかの差異があると考えるのが妥当のような気もしますがどうなんでしょう？

不思議(?)なのは、Filezillaでのサイトの設定画面では、最初の投稿にあるように、サーバー設定の「サーバのタイムゾーン オフセットの調整」はゼロのままです。それで左右ペインの日時が合っています。これは似て非なるものということになりそうですね。

**Comment by honeylover** [comment]
FFFTP上でタイムスタンプが1年前になっているときは、表示上だけでなく本当にそのタイムスタンプの年と見なしているようです。例えば、アップロード直後にミラーリングアップロードのリストを取ると、また同じものをアップロードしようとします。サーバーの方が1年古いからということでしょうね。で、そこはキャンセルをして、正常な年になるまで（今で言えば0時過ぎるまで）待ってから、再度ミラーリングアップロードのリストを取ると今度はそのファイルはリストアップされません。同一と見なされるということだと思います。

**Comment by sayurin** [comment]
https://github.com/sayurin/ffftp/blob/0fcd64c9568733e23ef54aaec5622ce1c9719ad5/filelist.cpp#L5421-L5442

１年繰り下げているのはこの個所。とくに後者のコードブロック。であれば問題は現在時刻が正しいかどうか。

**Comment by honeylover** [comment]
いろいろ調べていただきありがとうございます。
こちらの21日のファイルがサーバーに届いた時には22日で、それをFFFTPは去年のものと解釈する、という感じですかね。確かに後者部分が大いに関係していそうです。

テストバージョンでも作っていただけれるのであれば喜んで試してみたいと思います。
では、いま午前2時半過ぎで、今日はもう限界なので休みます。。。m(_ _)m
よろしくお願いします。

**Comment by sayurin** [comment]
時差がありますね。後日で構いませんのでお手数ですが、ffftpを使用してftpサーバー上に「フォルダ作成」を実行してください。その上で、作成されたフォルダの時刻がどのように表示されるか教えていただきたいです。
表示される時刻が操作を行った時刻と一致しない場合、何らかの設定が誤っていることになります。
一致した場合は…どうしたものか、もう少し考えます。

**Comment by honeylover** [comment]
フォルダ作成したところ、現地時間と同じように表示されています。
作成時刻は午前6時42分で、FFFTP上のフォルダのタイムスタンプも2018/04/27 6:42 と表示されています。
この作成を11時過ぎてから、つまり、こちらが27日で日本が28日になったときにどうなるかも見てみようと思います。

**Comment by honeylover** [comment]
11時になったのでフォルダ作成したところ、ファイルと同じく1年前のタイムスタンプ 2017/04/27 11:00 になりました。これが2018になるのは今から13時間後の今晩0時になろうかと思います。

**Comment by sayurin** [comment]
お手数かけました。質問文を再度読み直してようやく理解しました。

1. FTPはサーバーから渡された文字列を人間が目で判断する仕様で、設計された当初、タイムゾーンの概念は存在しませんでした。
2. RFC 3659（2007年）にタイムゾーンに対応したMLSDコマンドが提案されましたが、質問のサーバーは未対応なようです。ffftp側ではホスト設定の**可能であればMLSDコマンドで一覧を取得**を有効にすることで対応します。既定で有効となっているはずですが、設定を確認してください。
3. MLSD未対応のサーバーのためにffftpではホスト設定に**タイムゾーン**を用意しています。質問のサーバーはJST; 日本標準時とのことですので、**GMT +9:00**に設定する必要があり、既に設定されているとの認識です。

以上が前提条件で、サーバーから年情報が送られてこなかった際に年を推測する処理でホスト設定のタイムゾーンを考慮されていませんでした。
なお、ホスト設定のタイムゾーンを反映させる処理は年を決定した後になっていました。ちなみに、この処理はffftpがオープンソースとして公開された2011年から変更されていないようなので、それ以前からあるバグということになります。

**Comment by honeylover** [comment]
丁寧なお返事ありがとうございます。
1. なるほど・・・
2. LISTは不使用（だからMLSDも不使用）。NLST -R を使うようにしています。何かおかしかったからそのようにした記憶がありますが、やはり未対応だったわけですね。あとはやはりミラーリングでは再起検索の有無でリストが現れるまでの時間に驚くほどの差が出ますので現在の設定がベストだと思っています。
3. GMT +9:00 に設定済みです。

かなり昔からのバグということですが、このバグは直すことは可能でしょうか?

**Comment by sayurin** [comment]
もちろん頑張って直します！

**Comment by honeylover** [comment]
ありがとうございます！！
それにしても、他人のソースに手を加えるのは本当に簡単ではないんでしょうね。
どうかよろしくお願いします。
なお、明日は昼から夜中まで（日本だと日曜日0時から昼過ぎまで）ずっと外出ですのでもしテストが必要でも対応できません。m(_ _)m

**Comment by honeylover** [comment]
昨日作成したフォルダはやはりこちらの0時に年が正常に（2018年に）戻りました。
で、今さら思い出したのですが、日本はGWが始まりましたね。
デバッグ作業、どうぞごゆっくり。ご自分の時間を取ってくださいませ。

**Comment by sayurin** [comment]
https://github.com/sayurin/ffftp/releases/tag/test-%2332
@honeylover テスト版を作成したので、時間帯によって表示が改善されるか確認していただけないでしょうか。また接続した際に表示されるログから
```
>FEAT
211-Extended features supported:
 LANG EN*
 UTF8
 AUTH TLS;TLS-C;SSL;TLS-P;
 PBSZ
 PROT C;P;
 CCC
 HOST
 SIZE
 MDTM
 REST STREAM
211 END
```
の個所があるかと思いますので、この内容を教えていただけないでしょうか。

**Comment by honeylover** [comment]
ありがとうございます。テストしてみました。
今はこちらは4月29日午前3時半で、日本は同日の午後4時半ですので、今までならこの時間帯は問題は無かったのですが、このテスト版では、残念ながら2017年と表示されてしまいます。同じファイルをv3.2で見てみると2018になっています。今まで通りです。

あとログ内容ですがこれでいいでしょうか。
>FEAT
211-Features:
 LANG bg-BG;en-US*;es-ES;fr-FR;it-IT;ja-JP;ko-KR;ru-RU;zh-CN;zh-TW
 MDTM
 SSCN
 TVFS
 MFMT
 SIZE
 PROT
 CCC
 PBSZ
 AUTH TLS
 MFF modify;UNIX.group;UNIX.mode;
 REST STREAM
 MLST modify*;perm*;size*;type*;unique*;UNIX.group*;UNIX.mode*;UNIX.owner*;
 UTF8
 EPRT
 EPSV
211 End

それでは大変だと思いますがどうかよろしくお願いします。

**Comment by sayurin** [comment]
https://github.com/sayurin/ffftp/releases/tag/test-%2332
@honeylover テスト版を作り直しました。お手数ですが再度確認していただけないでしょうか？（＞＜
それとは別にMLST対応のftpサーバーなんですね。

**Comment by honeylover** [comment]
一つ思い出しました。
MLSDを使うようにすると、ミラーリングダウンロードのリストアップ中にいつも止まってしまうんです。いろんなディレクトリを見ていっている途中、
>MLSD
でピタッと止まってしまうんです。それで、それを使わないようにしたような記憶があります。そしてその時にいい意味で副作用的に分かったのが、再起検索があるとものすごくリストアップが速いし、ちゃんと最後までリストアップを完了してくれるということがありました。

test2のテスト結果は、MLSDコマンドを使うと2018年ですが、そうでない場合は2017年です。今は正常な時間帯で、v3.2ならMLSD使わなくて2018年表示です。

結構大きいサイトなのでリストアップで3分かかるか15分かかるかというのはかなり大きな差になるため、再起検索は使い続けたいですし、現状ではそうでなくてもMLSDが止まってしまうのは致命的なのでどうしようもないというのもあります。

引き続きよろしくお願いします。
今からちょっと出かけるので帰ってくる頃は現地と日本で日付がずれる頃になります。

**Comment by honeylover** [comment]
MLSDだとミラーリングダウンロードのリストアップの途中（数分経過した頃）でいきなり止まってしまうというのは、すでに何度も遭遇しています。MLSDを使わなければ大丈夫です。

私は再起検索を使いたいのでMLSDは使わなくていい（というか使うと不都合）のですが、MLSDを使いたい人もいるでしょうから、これについては今回の件とは別でISSUEとして挙げた方がいいのかもしれませんね。ただし、小規模サイトなら大丈夫なのでややこしいですけど。

**Comment by sayurin** [comment]
https://github.com/sayurin/ffftp/releases/tag/test-%2332
@honeylover 何度もすみませんが、テスト版を作り直しました。言い訳をすると日付解析のコードが最も長く、全体の数％を占めてます。処理は非常に複雑な記述がされ、効率もかなり悪いです。実のところ何がどうなっているのかよくわかっていません。

- test1： ftpサーバー側にタイムゾーン補正を入れました
- test2： タイムゾーン補正を外しました
- test3： クライアント側にタイムゾーン補正を入れました

どれかが当たりだと目論んでいるのですが…。

---
> いろんなディレクトリを見ていっている途中、
> \> MLSD
> でピタッと止まってしまうんです。

確かに再帰検索は有効ですね。ファイル数が多いと（？）`MLSD`が止まるんですね。本来、`MLSD`コマンドの方が解析しやすいはずで、何か問題を抱えているのかもしれません。

**Comment by honeylover** [comment]
うーん、test3も残念な結果に終わりました。いまこちらは29日午後2時過ぎ。日本は30日午前3時過ぎです。で、今作成したファイルをアップロードしたところ、2017年表示になりました。

ところで、そのファイルをTest1とTest2でも見てみたところ、全部2017年で、結果としてはTest1～Test3すべてがv3.2までの状況と同じです。
ところが、こちらの29日午前3時半頃にアップロードしたファイルに関しては違いがあります。
Test1だけは2018年ですが、Test2とTest3では2017年と表示されます。v3.2で見てもそのファイルは2018年表示でありTest1と同じということになります。

なんだかややこしくなってきました。ちなみに、どれもMLSDおよびLISTは使っていません。

>言い訳をすると日付解析のコードが最も長く、全体の数％を占めてます。処理は非常に複雑な記述がされ、効率もかなり悪いです。実のところ何がどうなっているのかよくわかっていません。

他人のソースの引き継ぎは大変ですよね。プログラミング自体に関しては全くの素人ではない（引き継ぎ経験あり）のでその大変さはよく分かります。それにしても、それこそ素人考えだと日付解析コードがもっとも長いというのは意外でした。お疲れ様です。

**Comment by sayurin** [comment]
お手数おかけします。

>

**Comment by honeylover** [comment]
こちらこそ感謝しております。

ところで、さっき思ったのですが、もしそちらに別環境が用意できるなら、そのPC（もしくはバーチャルPC）のタイムゾーンを「(UTC-04:00) クイアバ」にすれば、こちらと同じになるはずで、私の回答を待つ時間も節約できるんじゃないかなとか思いました。誤解無いように言いますが、こちらでテストするのがイヤとかそういうことではまったくありません。テストは喜んでさせていただきます。

**Comment by sayurin** [comment]
https://github.com/sayurin/ffftp/releases/tag/test-%2332
@honeylover 何度もすみません。簡単に解決すると思って手抜きしていました。ご指摘の通り、VMで環境構築して確認してみました。今度は手元の環境では西暦が一致することを確認したバージョンとなります。試していただけないでしょうか。
