### ISSUE TITLE
Private IPに対してUPnPを試行しない

### ISSUE THREAD

**Issue by sayurin** [sayurin/ffftp#44]
`非PASVモード時にUPnPの制御を試行する`が有効になっているとUPnPが試行されるが、リモートアドレスがPrivate IPの場合、外部アドレスを取得するべきではない。
多段NAT等があるので、条件を精査する必要がある。

cf. https://twitter.com/swingwings/status/1001874169745760256

**Comment by nomoto-neo** [comment]
VPN使用時もルーターの外部アドレスを取得するべきではないので同様にお願いします

**Comment by nomoto-neo** [comment]
@sayurin お返事ありがとうございます。
VPNはデフォルトゲートウェイが変更されて外に出て行く経路が変わるだけなので、FFFTPからみた接続先サーバーのIPアドレスは、グローバルアドレスのままで変わりありません。

自PCに割り当てられてるIPアドレスというのは、何で判断すれば良いでしょうか。
VPN接続している状態でのrouteコマンドか何かの結果を提供すれば分かりますか？

**Comment by sayurin** [comment]
> VPNはデフォルトゲートウェイが変更されて外に出て行く経路が変わるだけ

> VPN接続中は２つのローカルネットワークに同時につながった状態

この２ヶ所が矛盾してるかと。新たに割り当てられたローカルネットワーク、そこではデフォルトゲートウェイだけでなくIPアドレスやDNSも割り当てられていませんか？ その際に割り当てられているIPアドレスがPrivate IPかどうか、また割り当てられたDNSを使用してftpサーバーを検索するとPrivate IPが得られたりしませんか？ （というのが先のコメントです。）

**Comment by nomoto-neo** [comment]
話題がそれてしまってすみません。長くなりますが、参考までにVPN接続時の状況を説明します。

FTPサーバーへはグローバルIPアドレス指定で接続しています。
VPNサーバーを経由しない場合は、発信元のグローバルIPは、プロパイダからルーターに割り当てられたグローバルIPになります。
PC→ルーター→(インターネット)→FTPサーバー
VPN接続した場合は、全ての通信がVPNサーバー上でルーティングされて、FTPサーバー側から見るとVPNサーバーのグローバルIPが発信元として記録されます。
PC→ルーター→(インターネット)→外部VPNサーバー→(インターネット)→FTPサーバー

PC→ルーターのPrivate Networkは 192.168.3.0/24 ルーターのプライベートIPは 192.168.3.1 です。

PCからVPNサーバー（219.94.251.？？？）へ接続すると、PC上のVPNアダプタ→VPNサーバー間で 192.168.7.0/24 のローカルネットワークが張られて、PC側のアダプタには 192.168.7.100 というローカルIPがもらえます。その状態でグローバルIPに対してFTPやHTTPの接続をすると、VPNサーバー上ではローカルIPからのデータとして届くのでパケットをNATルーティングして自分のIPアドレスを発信元として外部に送り出しています。

**Comment by nomoto-neo** [comment]
VPN接続していない時の ipconfig /all と route print はこうです。

Wireless LAN adapter ワイヤレス ネットワーク接続:

   接続固有の DNS サフィックス . . . : flets-east.jp
   説明. . . . . . . . . . . . . . . : Intel(R) Centrino(R) Advanced-N 6205 #
   物理アドレス. . . . . . . . . . . : 84-3A-4B-6D-81-94
   DHCP 有効 . . . . . . . . . . . . : はい
   自動構成有効. . . . . . . . . . . : はい
   IPv4 アドレス . . . . . . . . . . : 192.168.3.10(優先)
   サブネット マスク . . . . . . . . : 255.255.255.0
   リース取得. . . . . . . . . . . . : 2018年8月9日 23:48:51
   リースの有効期限. . . . . . . . . : 2018年8月10日 14:18:53
   デフォルト ゲートウェイ . . . . . : 192.168.3.1
   DHCP サーバー . . . . . . . . . . : 192.168.3.1
   DNS サーバー. . . . . . . . . . . : 192.168.3.1
   NetBIOS over TCP/IP . . . . . . . : 有効
   接続固有の DNS サフィックス検索の一覧:
                                       flets-east.jp
                                       iptvf.jp

IPv4 ルート テーブル
===========================================================================
アクティブ ルート:
ネットワーク宛先        ネットマスク          ゲートウェイ       インターフェイス  メトリック
          0.0.0.0          0.0.0.0      192.168.3.1     192.168.3.10     25
        127.0.0.0        255.0.0.0            リンク上         127.0.0.1    306
        127.0.0.1  255.255.255.255            リンク上         127.0.0.1    306
  127.255.255.255  255.255.255.255            リンク上         127.0.0.1    306
      169.254.0.0      255.255.0.0     192.168.3.12     192.168.3.10     26
      192.168.3.0    255.255.255.0            リンク上      192.168.3.10    281
     192.168.3.10  255.255.255.255            リンク上      192.168.3.10    281
    192.168.3.255  255.255.255.255            リンク上      192.168.3.10    281
        224.0.0.0        240.0.0.0            リンク上         127.0.0.1    306
        224.0.0.0        240.0.0.0            リンク上      192.168.3.10    283
  255.255.255.255  255.255.255.255            リンク上         127.0.0.1    306
  255.255.255.255  255.255.255.255            リンク上      192.168.3.10    281
===========================================================================

**Comment by nomoto-neo** [comment]
VPN接続しているときは、こうです。
　
PPP アダプター VPN接続:
　
   接続固有の DNS サフィックス . . . :
   説明. . . . . . . . . . . . . . . : VPN接続
   物理アドレス. . . . . . . . . . . :
   DHCP 有効 . . . . . . . . . . . . : いいえ
   自動構成有効. . . . . . . . . . . : はい
   IPv4 アドレス . . . . . . . . . . : 192.168.7.100(優先)
   サブネット マスク . . . . . . . . : 255.255.255.255
   デフォルト ゲートウェイ . . . . . : 0.0.0.0
   DNS サーバー. . . . . . . . . . . : 210.224.163.4
                                       210.224.163.3
   NetBIOS over TCP/IP . . . . . . . : 有効
　
Wireless LAN adapter ワイヤレス ネットワーク接続:
　
   接続固有の DNS サフィックス . . . : flets-east.jp
   説明. . . . . . . . . . . . . . . : Intel(R) Centrino(R) Advanced-N 6
   物理アドレス. . . . . . . . . . . : 84-3A-4B-6D-81-94
   DHCP 有効 . . . . . . . . . . . . : はい
   自動構成有効. . . . . . . . . . . : はい
   IPv4 アドレス . . . . . . . . . . : 192.168.3.10(優先)
   サブネット マスク . . . . . . . . : 255.255.255.0
   リース取得. . . . . . . . . . . . : 2018年8月9日 23:48:51
   リースの有効期限. . . . . . . . . : 2018年8月10日 14:18:53
   デフォルト ゲートウェイ . . . . . : 192.168.3.1
   DHCP サーバー . . . . . . . . . . : 192.168.3.1
   DNS サーバー. . . . . . . . . . . : 192.168.3.1
   NetBIOS over TCP/IP . . . . . . . : 有効
   接続固有の DNS サフィックス検索の一覧:
                                       flets-east.jp
                                       iptvf.jp
　
IPv4 ルート テーブル
----
アクティブ ルート:
ネットワーク宛先        ネットマスク          ゲートウェイ       インターフェイス  メトリック
          0.0.0.0          0.0.0.0      192.168.3.1     192.168.3.10   4250
          0.0.0.0          0.0.0.0            リンク上     192.168.7.100     21
        127.0.0.0        255.0.0.0            リンク上         127.0.0.1   4531
        127.0.0.1  255.255.255.255            リンク上         127.0.0.1   4531
  127.255.255.255  255.255.255.255            リンク上         127.0.0.1   4531
      169.254.0.0      255.255.0.0     192.168.3.12     192.168.3.10   4251
      192.168.3.0    255.255.255.0            リンク上      192.168.3.10   4506
     192.168.3.10  255.255.255.255            リンク上      192.168.3.10   4506
    192.168.3.255  255.255.255.255            リンク上      192.168.3.10   4506
    192.168.7.100  255.255.255.255            リンク上     192.168.7.100    276
   219.94.251.？？？  255.255.255.255      192.168.3.1     192.168.3.10   4251
        224.0.0.0        240.0.0.0            リンク上         127.0.0.1   4531
        224.0.0.0        240.0.0.0            リンク上      192.168.3.10   4509
        224.0.0.0        240.0.0.0            リンク上     192.168.7.100     21
  255.255.255.255  255.255.255.255            リンク上         127.0.0.1   4531
  255.255.255.255  255.255.255.255            リンク上      192.168.3.10   4506
  255.255.255.255  255.255.255.255            リンク上     192.168.7.100    276
----

**Comment by sayurin** [comment]
説明ありがとうございます。なんとなくわかりました。

本Issueでは「本来PORTモード接続（非PASVモード接続）可能な環境において、UPnP機能が要因で接続できなくなる状況を救う（UPnPを無効化することでPORTモード接続を実現する）」を目的としています。 @nomoto-neo さんの使われているVPN環境ではUPnPを無効化しさえすればPORTモードで接続可能なのでしょうか？

YesだとしてもVPN下の検出は難しい気はしています。「PPP アダプター VPN接続」とか検出は可能ですが、他にもVPNの実現手段はありますし。

**Comment by sayurin** [comment]
説明ありがとうございます。

となると、UPnP機能をデフォルトでoffにするのも一つの選択肢としてありそうですね。互換のため既存の設定については変更できませんが。
