### ISSUE TITLE
FTP側のファイル・フォルダが真っ白で出てこない

### ISSUE THREAD

**Issue by yoshiyuki-nakase** [sayurin/ffftp#45]
version3.3です。ホストの設定の暗号化タブで「FTPS(Explicit)で接続」にチェックが入っているとFTP側のファイルが真っ白になります。「暗号化なしで・・・」にチェックを入れると表示される。version3.2では問題なく表示されていた。

**Comment by sayurin** [comment]
実行環境を教えてください。
また環境設定でデバッグにチェックを付けた状態で、ログインし直して、その際に表示されたログを貼り付けてください。内容を確認したいと思います。

---
なお[v3.2からv3.3への変更点](https://github.com/sayurin/ffftp/compare/v3.2...v3.3)は

 - コンパイルオプションの変更
 - ファイル一覧でのタイムスタンプの計算方法の変更
 - バージョン表示

しかありません。v3.3で表示されなかったのは別の要因の可能性があります。

**Comment by yoshiyuki-nakase** [comment]
環境は「Win7 32bit / 光回線」です。
ファイル・フォルダ数が少ないと問題なく表示されますが、多いと表示されません。
また「Win10 64bit / 光回線」ではファイル・フォルダ数が多くても表示されました。

環境設定のデバッグですが、どのタブにありますか？
すべてのタブを見ましたが見当たりませんでした。

よろしくお願いします。

**Comment by sayurin** [comment]
#38 と同件でしょうか？ そうであればホスト設定の `高度` タブ `可能であればMLSDコマンドで一覧を取得` のチェックを外した場合に改善されますでしょうか？
デバッグは環境設定の `その他` タブの右下にあります。

**Comment by yoshiyuki-nakase** [comment]
>MLSDコマンドで一覧を取得 のチェックを外した場合に改善されますでしょうか？
いえ、改善されませんでした。

デバッグログの内容です。
## DEBUG MESSAGE ON ! ##
FFFTP Ver.3.3 32bit Copyright(C) 1997-2010 Sota & cooperators.
Copyright (C) 2011-2018 FFFTP Project (Hiromichi Matsushima, Suguru Kawamoto, IWAMOTO Kouichi, vitamin0x, unarist, Asami, fortran90, tomo1192, Yuji Tanaka, Moriguchi Hirokazu, Fu-sen, potato).
Copyright (C) 2018, KURATA Sayuri.
INIファイル指定: xxx
## Tmp =xxx
## Help=C:\Program Files\ffftp\ffftp.chm
デフォルトのマスターパスワードが使われます.
マルウェアの攻撃を防ぐため,固有のマスターパスワードを設定することをおすすめします
----------------------------
FTP over Explicit SSL/TLS (FTPES)を使用します.
ホスト xxx を探しています. (TCP/IPv4)
ホスト xxx を探しています. (TCP/IPv6)
ホスト xxx が見つかりません. (TCP/IPv6)
ホスト xxx (xxx.xxx.xxx.xxx (21)) に接続しています. (TCP/IPv4)
接続しました. (TCP/IPv4)
220 ProFTPD 1.3.5a Server (SAKURA Internet FTP Server) [::ffff:xxx.xxx.xxx.xxx]
>AUTH TLS
234 AUTH TLS successful
ログインできません.
## Skt=1404 : Socket closed.

**Comment by sayurin** [comment]
ファイル数が少ないとログインできるのでしょうか？ ちょっと何を言っているのかよくわかりませんでした。

**Comment by yoshiyuki-nakase** [comment]
ファイル数やフォルダ数は無関係でした。
失礼しました。

暗号化なしで接続を許可：チェックを外す
FTPS(Explicit)で接続：チェックする
FTPS(Implicit)で接続：チェックを外す
この状態で接続すると真っ白になってしまいます。

**Comment by yoshiyuki-nakase** [comment]
Version3.2、3.1と落として試してみましたが「暗号化なしで接続を許可」にチェックがついていると
FTP側のペインが真っ白になってしまいます。
ホストも作り直してみましたが同症状です。
一度、PCを変えて試しています。

**Comment by sayurin** [comment]
さくらインターネットとのことですので、

[さくらインターネットが提供する各種サービスにおけるTLS1.0/1.1無効化の詳細](https://help.sakura.ad.jp/hc/ja/articles/360000057382) 

この問題が影響していますでしょうか？ これによりますとTLS 1.2についてWindows 10は標準で有効化されており、Windows 7は標準で無効化、インターネットオプションから有効化する必要があります。

**Comment by yoshiyuki-nakase** [comment]
他のPCでも試してみましたが、やはりWin10では繋がりますが、Win7ですと駄目でした。

インターネットオプションに下記の項目がありましたがすべてチェックがついていました。
・「TLS 1.0を使用する」
・「TLS 1.1の使用」
・「TLS 1.2の使用」
また、1.0と1.1のチェックだけを外して試してみましたが同症状でした。
一度、さくらインターネットに聞いてみます。
ありがとうございます。

**Comment by sayurin** [comment]
念のため確認です。問題のPCで、Internet Explorerを使用して [さくらインターネット](https://www.sakura.ad.jp/) を開くことはできますでしょうか？ また先のページで指摘されているような警告は表示されます／されないでしょうか？

当方でもWindows 7を使用して確認してみます。

**Comment by yoshiyuki-nakase** [comment]
>問題のPCで、Internet Explorerを使用して さくらインターネット を開くことはできますでしょうか？

問題なく開くことができました。

かなり古い記事ですが、このあたりと関係ありますか？
https://ja.osdn.net/projects/ffftp/forums/27005/34808/

**Comment by sayurin** [comment]
関係なさそうです。先ほど挙げていただいたログによるともっと手前の部分で止まっています。

**Comment by yoshiyuki-nakase** [comment]
さくらレンタルサーバより返信がありました。
ご指摘の通り「TLS1.2」に対応していないアプリの場合、接続できなくなるとのことでした。

FFFTPはTLSの設定はどこかでできますか？

**Comment by sayurin** [comment]
ffftpはOSの設定に従うように実装したつもりです。ですが先のコメントの通りの動作であればインターネットオプションには従っていないようですので、状況を確認します。

---
インターネットオプションとは別にレジストリ設定もある模様。

- [TLS 1.2 への移行を推奨しています](https://blogs.technet.microsoft.com/jpsecurity/2017/07/11/tlsmigration/)
- [How to restrict the use of certain cryptographic algorithms and protocols in Schannel.dll](https://support.microsoft.com/en-us/help/245030/how-to-restrict-the-use-of-certain-cryptographic-algorithms-and-protoc)

**Comment by sayurin** [comment]
@yoshiyuki-nakase もし試していただけるのでしたら次のレジストリを設定してみてください。

```
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Client
名前 DisabledByDefault、種類 DWORD、値 0
```

**Comment by yoshiyuki-nakase** [comment]
レジストリを追加したところ無事に接続できました！

（ケース1）
1．レジストリを追加
2．PC再起動
3．FFFTPから接続ができるようになる
（ケース2）
1．レジストリを削除
2．PC再起動
3．FFFTPから接続できなくなる

**Comment by sayurin** [comment]
情報提供ありがとうございました。手順についてはwikiの [TLS 1.2対応について](https://github.com/sayurin/ffftp/wiki/TLS-1.2) で順次まとめていきます。
