### ISSUE TITLE
[ヘルプ] > [Q&A集(インターネットに接続します)] のアクセスキー

### ISSUE THREAD

**Issue by Phroneris** [sayurin/ffftp#70]
https://github.com/sayurin/ffftp/blob/7f0cd535315f438da73c042288f06e0d36e708bc/Resource/ffftp.ja-JP.rc#L176

`(T)`は、`(&T)`の脱字かと思われます。

**Comment by sayurin** [comment]
指摘の通りですが、そもそもメニュー項目名とクリックした際の挙動が一致していませんね。URLを開いてもQ&Aはありませんし…。

**Comment by Phroneris** [comment]
ああ、それはそれで確かに感じました。デフォルトで表示される`readme.md`もなければ、[Wiki](https://github.com/sayurin/ffftp/wiki)へのリンクとかもないですし（WikiもどのみちQ&Aは載ってないですが）。

**Comment by sayurin** [comment]
引き継ぎ元の https://ja.osdn.net/projects/ffftp/ にも対応しそうなページはありませんね…。原作者 Sotaさんの http://www2.biglobe.ne.jp/sota/ffftp.html にはQ&Aページがありますね…。

Readme.mdを用意していないのは、リポジトリ直下に多数のファイルが存在するとReadme.mdが読みづらいページ構成なので悩んだ上、作っていません。ソースコードを`src`ディレクトリへ移動したら作ろうかと。

さてどうしたものか…。
