### ISSUE TITLE
OpenSSL 1.1.1の対応予定について

### ISSUE THREAD

**Issue by NiGSan** [sayurin/ffftp#72]
OpenSSL 1.1.0 から 1.1.1へのアップデート予定や、
TLS1.3やSHA512などの追加サポート予定はありますか？

また少しなにかお手伝い出来れば、させて頂きたいのですが…。

**Comment by sayurin** [comment]
申し出ありがとうございます。 d494ceb5af5de779d31f5c64bc9f8bfc848fd8b8 にてOpenSSLを削除し、Windows搭載のSSPIに切り替えています。そのため、TLS 1.3やSHA512対応はWindows依存となっています。[TLS-1.2](/sayurin/ffftp/wiki/TLS-1.2) でTLS 1.2の有効化方法をまとめています。なお、WindowsにはTLS 1.3は搭載されていなさそうです。（Windows 10 1810で搭載されるかも？）
